[build-system]
requires = ["setuptools>=68", "wheel", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "openmower-cli"
dynamic = ["version"]
requires-python = ">=3.10"

[tool.setuptools_scm]

[project.scripts]
openmower = "openmower_cli.__main__:main"
