name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'feature/*'

jobs:
  pre-commit:
    name: "Run Pre-Commit Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
  build:
    name: "Build Artifacts"
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=./artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openmower-cli
          path: artifacts/
  tagged-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: build
    steps:
      - name: Download artifacts from build stage
        uses: actions/download-artifact@v4
        with:
          name: openmower-cli
          path: artifacts
      - name: Compress release directory into a versioned ZIP file
        run: cd artifacts && zip -r "../openmower-cli-${{ github.ref_name }}.zip" .
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "openmower-cli-${{ github.ref_name }}.zip"
